# Generated by Django 3.0.3 on 2020-04-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RainBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RainDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('data', models.FloatField()),
                ('rainbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='web.RainBot')),
            ],
        ),
    ]
